### ISSUE TITLE
Split download versus building?

### ISSUE THREAD

**Issue by danholdaway** [JCSDA/jedi-stack#34]
How straightforward would it be to split the downloading and building. E.g.

Script 1: Download all the packages to be installed and stage somewhere.

Script 2: Build the packages from staged location (rather than with in-line remote get).

Machines such as Theia do not allow for wget and cloning from github is extremely slow. It would be useful if I could run the first script to download step on another machine, scp the downloads to Theia and then run the build on Theia using the second script.

**Comment by mmiesch** [comment]
@danholdaway - Sure - good idea.   However, instead of having two different scripts, perhaps it would be easier to just add a DOWNLOAD_ONLY option in the config files.  Then, if this is set to Y or T, the scripts would just download the packages and exit.  Then, when you run it again with that variable set to N or F, it would see that the packages are already there and will not download them again (this capability is already implemented).  So, in this case, you could download all the packages into a pkg directory on your local machine and then tar it up and put it in the pkg directory of jedi-stack.  Does this sound like it will do what you want?

**Comment by danholdaway** [comment]
@mmiesch sounds good, thanks. That would work.

**Comment by mmiesch** [comment]
@danholdaway - I'm going to close this because this capability was added together with the eckit 1.1 update.  Now one can just set DOWNLOAD_ONLY=T to just download.  Then some manual judgement can still be used to determine what really needs to be bundled up and sent to Theia.  Most notably, for boost, you only need to include the include files in a tar ball that you then send to Theia.
