### ISSUE TITLE
Find eckit, fckit

### ISSUE THREAD

**Issue by mmiesch** [JCSDA/jedi-stack#4]
We should fork and modify ecbuild as needed to detect whether eckit and fckit are already there in the environment.  If so, then do not build them.  ecbuild may already have this capability - we should investigate.

@aerorahul - I'm creating this issue int the jedi-stack repo for now because it's related to the build and because we do not yet have a fork of ecbuild.  Feel free to add yourself to the assignee list if you have the time & the inclination to work on it.

**Comment by aerorahul** [comment]
@mmiesch When eckit and fckit are built, these `pkg-config` parseable files are created and exist in 
`$ECKIT_PATH/share/eckit/cmake/eckit-config.cmake`
`$FCKIT_PATH/share/fckit/cmake/fckit-config.cmake`

The way to use them in CMakeLists.txt for the bundles, is to 
`pkg-config` knows how to get the information

e.g.
```
find_package(PkgConfig REQUIRED)
pkg_check_modules(ECKIT REQUIRED)
```
This sets up the variables ECKIT_INCLUDE_DIRS, ECKIT_FOUND, etc.

An alternative is to write a `FindECKIT.cmake`, that does the above given `ECKIT_PATH` or `ECKIT_ROOT`

This is do-able in a day's work.  May be on a day with downtime.

**Comment by markjolah** [comment]
Doing a cleanup of ecbuild related issues, and trying to get a handle on what issues are still relevant:

This particular problem should actually be even simpler then indicated Rahul's comments as those config files are native CMake config files, not `pkg-config` files. All we need is
`find_package(eckit REQUIRED)`

The open question may be how those packages (eckit/fckit) are installed.  If a `make install` has been performed then the generated package configs will be installed to the CMAKE_INSTALL_PREFIX.  As long as this prefix is in the search path of later CMake invocations, the packages should be found and configured just fine.

CMake also provides a mechanism to find config files from the Build directory of a package, but ecbuild turns off this option by default.

If this issue is still causing problems, please point me to the relevant errors and we can figure it out from there.

**Comment by mmiesch** [comment]
I'm not sure I'm following.  An example use case is when different fckit modules are installed in different directories (e.g. ecmwf or jcsda).  If I load one of these modules and then run ecbuild on a bundle, then it should detect the presence of fckit from PATH and LD_LIBRARY_PATH and then not build it locally - the CMAKE_INSTALL_PREFIX variable cannot be relied on to find fckit in that case because it is going to be different than what it was in the past when the modules were built.

**Comment by markjolah** [comment]
Sorry that wasn't the clearest explanation and yes the CMAKE_INSTALL_PREFIX I was referring to is just the location where eckit was installed.

The details of the `find_package()` search procedure are here: 
https://cmake.org/cmake/help/latest/command/find_package.html?highlight=i#search-procedure

It looks like rule #5 will apply for this use case.  The `module load eckit` sets the `PATH` environment variable which will then be used by `find_package(eckit)` as the prefix to locate `<prefix>/share/eckit/cmake/eckit-config.cmake`

I looked at the eckit-config.cmake and fckit-config.cmake files that are provided in the jedi-stack modules and they look OK.

I would expect that this should work correctly in the default usage and find the already installed versions of the libraries.

If there is a specific case where it's not working let me know and I can debug it.

**Comment by mmiesch** [comment]
Now that I think about it, maybe the issue wasn't finding eckit and fckit in the first place - it was merely to use the result of that as a condition to trigger a build or not.   For example, on my Mac I have fckit installed in /usr/local.  If I comment out the build of fckit in the bundle, everything compiles and runs fine.   Then, if I uncomment the fckit build line in the bundle, it should still skip the build because it's already there.  But it doesn't do that - instead it does a fresh clone of fckit in the bundle directory and builds it again.  So, I think we just need to put a conditional statement in the bundle builds to skip the build if fckit is found

**Comment by markjolah** [comment]
When CMake finds a package via `find_package()` in config file mode, it sets `<PkgName>_FOUND` and `<PkgName>_DIR` variables. See:
https://cmake.org/cmake/help/latest/manual/cmake-packages.7.html#config-file-packages

`ecbuild_bundle()` does not check for these variables (although it could be made to).  It does respect the variable `BUNDLE_SKIP_<UPPER-CASE-PKG-NAME>`.

I see three options:
1. Wrap call to `ecbuild_bundle()` in a `if(NOT eckit_FOUND)` block
2. Use a similar conditional to set `BUNDLE_SKIP_ECKIT`
3. Modify ecbuild_bundle command to look for and respect value of `<Pkg-Name>_FOUND`

Probably options #1 or #2 are preferable and the choice depends on how you want the bundle's `CMakeLists.txt` to look.

**Comment by mmiesch** [comment]
Option 1 is what I had in mind.  I find it a little more intuitive than option 2 but either would work.  A problem with option 3 is that you **do** want projects such as ufo to build, even if they are already there.  Option 1 and 2 are transparent - a nice feature - you can easily  modify it if you want to force a new build on top of the old one.

**Comment by ytremolet** [comment]
I don't think we want the behavior to be different depending on the project. So I don't think rebuilding ufo even if it's found while not rebuilding others is a good idea.
And if eckit/fckit is found, the system still needs to check that it's the same branch/tag than what is requested in the bundle. Otherwise we'll get cases where people make a change but the code runs without them.
So really, what is in the bundle should be built and used.

**Comment by mmiesch** [comment]
I think the situation is a little different with eckit and fckit because these are installed more often than other jedi packages like ufo or oops.  For example, let's say a user has some tagged version of fckit available in /usr/local or by loading a module.  If the bundle builds fckit as well, I find that ecbuild can get confused with which version of the .mod files to use.  This is less of a problem with eckit but still, if eckit is in the path then it shouldn't be rebuilt, unless the version in the bundle is different from the version that's available.

**Comment by ytremolet** [comment]
If we have the capability to rebuild if the version is different then it should work if it's the same version but that's not even the concern.

The bundle should build what it's told to build. Otherwise we don't have control when we want to make changes and we introduce potential for hidden errors and weird behaviors. If something should not be built it should not be in the bundle. 

In our controlled environment, the easiest is to not pre-install what is in the bundles. So eckit can be pre-installed, everything else should be in the bundle and not pre-installed. If people want to pre-install more they will have to write their own bundle and be responsible for it but we cannot support all combinations.

Otherwise we should probably pre-install crtm because very people are modifying it, and it takes a lot longer to download, compile and install than fckit. And then somebody will do the same with fv3 because they work with the obs but don't modify the model... And we end up not knowing what is running because our build system makes hidden decisions.

**Comment by mmiesch** [comment]
Ok - I'm not bothered by the current system of just commenting or uncommenting each build one wants to do.  That certainly gives you the most control.  I think I just created this issue based on discussions we were having but if others want to close it, I would be ok with that.

**Comment by markjolah** [comment]
Actually the ecbundle is smarter than we may be giving it credit for.  From reading the code I think if the package is added with a `ecbuild_bundle()` the bundle CMake build itself as well as all of the other bundled repos will prefer the bundled versions over others (it will fall back to a normal search procedure if a needed package is not found in the bundle).  This technology is partly what causes problems with outside third party packages like LAPACK, but as far as the bundled repos it should just work the way Yannick would like it, no matter what repos are actually installed to the system.

My thought is we can close this issue, and just keep installing eckit in the jedi-stack, and leave it commented out in the bundles.  That way if someone wants to try a new version of eckit they can just uncomment, add the right branch name and it should "just work".

**Comment by markjolah** [comment]
On further thought the only reason to add the conditional compilation of eckit in, as discussed in the method above might be for use on systems that don't natively supply eckit.  The container and module environments are all going to be providing eckit via JEDI stack.  It seems the only systems that wouldn't have eckit would be for people trying to install to linux systems that are not using the 'lmod' modules package, e.g., my linux laptop.  But in my case  I just have eckit installed natively to the system, and other users following this path would be considered "expert" users and therefore could be reasonably expected to know to uncomment the eckit bundle build line for their specific use case.  Therefore the conclusion is the same, and we can keep the bundles as they are.

**Comment by markjolah** [comment]
I'm closing this issue as I believe we have resolved it based on the above conversation.  Please reopen if there are additional considerations I have overlooked.
