### ISSUE TITLE
LD variable for clang on Ubuntu

### ISSUE THREAD

**Issue by benjaminmenetrier** [JCSDA/jedi-stack#80]
I tried to install the modules with clang-9/openmpi-3.1.5 today on my machine (Ubuntu 18.04).
To make it work, I had to change the file `modulefiles/core/jedi-clang/jedi-clang.lua`. Instead of:
```
setenv("LD",  "clang")
```
I had to set:
```
setenv("LD",  "ld.lld-9")
```
Indeed, for most modules the `configure` step with `clang` as a linker prints:
```
checking if the linker (clang) is GNU ld... no
```
and the build crashes, whereas with `ld.lld` as a linker I get:
```
checking if the linker (ld.lld-9) is GNU ld... yes
```
and the build is succesfull.

Unfortunately, the linker name `ld.lld-9` is specific to the `clang` version, and I don't know how to make it generic.

**Comment by srherbener** [comment]
@benjaminmenetrier instead of calling ``module load jedi-clang`` explicitly, I've been calling ``module load jedi/clang-mpich``. When jedi/clang-mpich is loaded, LD gets set to mpicc in my environment and this works for building.

Currently, I am getting the jedi/clang-mpich module by adding ``/Users/stephenh/projects/jedi-stack/modulefiles/apps`` to my MODULEPATH. That is, pointing MODULEPATH  to the ``modulefiles/apps`` directory in my clone of jedi-stack. This was the methodology a while ago, and we should probably update the jedi-stack process so that the ``modulefiles/apps`` lua scripts get installed in the target directory (typically, /opt/modules).

**Comment by mmiesch** [comment]
In my opinion, trying to keep a generic version of the apps directory that works across all platforms is probably more trouble than it's worth.  As Steve was saying, I almost always customize the apps meta-module files for each system - I'm maintaining probably a dozen stacks and no two of them look alike at that high level.  This includes loading local modules for cmake, git, python, etc.  I have not bothered to crate branches or pull requests for each one of these.  So, if you need to change the LD flag for a given platform, I would just do that in the high-level metamodule, in this case apps/jedi/clang-mpich.

**Comment by benjaminmenetrier** [comment]
OK, I'll do that. Thanks for your feedback, I'm closing the issue.
