### ISSUE TITLE
BUFRLIB breaking container builds

### ISSUE THREAD

**Issue by mmiesch** [JCSDA/jedi-stack#84]
I believe the latest CMake changes to bufrlib are breaking my container builds.  This is the type of error I see, both for GNU and Intel compilers:
~~~~~
-- Configuring done
CMake Error:
  Error evaluating generator expression:

    $<Fortran_COMPILER_ID:GNU>

  Expression did not evaluate to a known generator expression


-- Generating done
-- Build files have been written to: /root/jedi-stack/pkg/bufrlib/_build
~~~~~

I'm using CMake 3.13.  Any idea what might be going wrong?

**Comment by srherbener** [comment]
Looks like this statement showed up in JCSDA/bufrlib#9 which was almost two weeks ago. I think it is testing if the Fortran_COMPILER_ID variable is set to "GNU".

I'm pretty sure I have built on my iMac and MacBook since this PR got merged and it worked. I'm using cmake 3.15.5, so maybe this syntax isn't compatible with version 3.13.

**Comment by mmiesch** [comment]
Thanks @srherbener - is that the case, @markjolah?  I can easily install whatever version of cmake I want in the container.  Is there a preferred, stable version?  Maybe 3.16?
